### ISSUE TITLE
Request for a better form of pipenet step (dict instead of list)

### ISSUE THREAD

**Issue by pushkarjain** [arundo/adtk#16]
The pipenet steps return a list of dictionaries with the key-value pairs indicating the start, end and the method/model used.  That means that to edit any particular step in the pipeline, one has to use index of the list to query the step and then modify it. 

One possible solution can be is to use the `name` as the `key`, and the values can be a dictionary with keys 'model' and 'input'. It might be more user-friendly to identify and query different nodes. 

In the attached image, the pipenet summary can be
`{'regression_residual':{'model': <value>, 'input':original}, ...}`

<img width="1475" alt="adtk_issues" src="https://user-images.githubusercontent.com/41306045/69737279-c10d5900-10f9-11ea-8942-e279c8e83010.png">

**Comment by tailaiw** [comment]
@pushkarjain Thanks for raising this issue. With a second thought, I agree with you that **list** is not a good choice of the `steps` attribute of pipenet class, because the indices do not have an intuitive meaning. Your suggestion, a **dict** with "name" as keys is a more intuitive data structure, in particularly convenient for querying nodes. We will add this to our roadmap of the next release.

**Comment by tailaiw** [comment]
fixed by #19
