### ISSUE TITLE
Support for Python 3.5 to allow deployment on GCP ML Engine runtime version 1.14

### ISSUE THREAD

**Issue by marktibbetts** [arundo/adtk#2]
Would like to use ADTK with GCP ML Engine but their current runtime framework (1.14) only supports Python 3.5. ADTK specifies Python >=3.6, so what are the options for making compatible with Python 3.5 or do we need to wait until GCP ML Engine runtime supports Python 3.6?

**Comment by tailaiw** [comment]
@marktibbetts thanks for raising this up. We were not aware of the mentioned limitation of Google Cloud Platform ML Engine. This is definitely a strong reason to consider a Python 3.5 support of ADTK. 

There are two known issues to deal with if we want to make it Python 3.5 compatible:

1. `dict` objects are insertion ordered since Python 3.6. Some features of ADTK requires `dict` objects to be insertion ordered. We may change them to `collections.OrderedDict` for Python 3.5 support. I think that is totally doable.

2. The pandas dependency is currently set as `>=0.25`. According to [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/install.html), pandas 0.25 supports python 3.5.3 and above. However, I noticed that the default Python3 on Ubuntu 16.04 is Python 3.5.2, and I suspect that is what GCP ML Engine is using. If that is the case, we need to support earlier versions of pandas dependency so you may use ADTK on at least Python 3.5.2.

    The reason of the current pandas 0.25+ dependency was we found a bug in 0.24 impacting some important features of ADTK and it seems fixed since 0.25. In particular, [`pandas.DataFrame.rolling`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html) does not set rolling interval open/closed as specified by option `closed` when the rolling window is offset-based. This would make [`DoubleRollingAggregate`](https://github.com/arundo/adtk/blob/v0.3/src/adtk/transformer/transformer_1d.py#L564) and quite a few associated detectors return unexpected results.

We will look into this and keep you updated here. Thanks again for raising the issue.

**Comment by tailaiw** [comment]
Issue resolved by #4
