### ISSUE TITLE
Ways to Ignore Known Outliers

### ISSUE THREAD

**Issue by yy910616** [arundo/adtk#42]
Hello Arundo Team,
I'm wondering if you have any inputs on this question.
I've been using ADTK on some highly seasonal (freq=7) e-commerce data. Now, e-commerce is heavily influenced by holidays. As you can see in the picture attached, there are two large spikes around Thanksgiving and Christmas. 

![adtk](https://user-images.githubusercontent.com/47798437/72003615-bf19d800-3217-11ea-8e3a-681f1eb3507c.png)

The problem is that I'm not so interested in the holiday spikes, but the __smaller outliers__ in the data. In a way, the two large peaks "drowns" out all other outlier effects. (Assuming something like Quantitle Detector is used).

One of the solution I've been testing is calculating weights for each holiday, then calculating a "fake" number by removing the holiday effects. But such solution seems to be outside the scope of ADTK.

Is there anything inside the ADTK package that might help address this issue? I've tried using DoubleRollingAggregate on the deseasonalize data, but it doesn't seem to help. I can also shorten the time window, but seems like a less than ideal solution.

Have you encounter similar problems before? Any guidance here would be greatly appreciated.

Thank you

Edit: 
Attached some data
[data.xlsx](https://github.com/arundo/adtk/files/4036682/data.xlsx)

**Comment by tailaiw** [comment]
@yy910616 An immediate answer to me is to use GeneralizedESDTestAD instead of QuantileAD if you believe your seasonal decomposition residual should be normally distributed if no anomaly exists. Generalized ESD test iteratively removes outliers that cannot pass the hypothesis test, so if there were points that are anomalous but not so extreme as some others, it should also be detected after the extreme ones got removed. 

I tested it on your data, it seems its output only differs from the output from InterQuatileRangeAD by one point (both models used default settings). 
![image](https://user-images.githubusercontent.com/29800495/72021579-f4ccba00-3233-11ea-881d-8f4ed929bd39.png)

It is expected by me because I don't see which points are the "smaller outliers" you mentioned by eyeballing the data. All data points except the two peaks look like normal noise to me. Maybe you can tell something different because you have more insight to the data?

**Comment by yy910616** [comment]
Hi @tailaiw,
Thank you for the quick reply.
The GeneralizedESDTestAD is a great suggestion. I haven't looked into it much yet but based on what you're describing, I think we can definitely use it to solve some problems.

For our specific scenario, I actually managed to solve it with a simpler method. Basically I run the seasonal transform first, then replace the dates where I don't want to see with np.nan, and feed the data back into QuantileAD. The result looks something like this.

![image](https://user-images.githubusercontent.com/47798437/72073305-a82dc100-32bd-11ea-9320-d67566486c85.png)

Turns out that while ClassicalDecompose method requires continuous data, QuantitleAD doesn't. 👍 This solves our issue of removing known outliers quite nicely.

Thank you again for you reply!
