### ISSUE TITLE
Add requirement.txt

### ISSUE THREAD

**Issue by rpanai** [arundo/adtk#76]
Hi, I'm trying to build a conda-forge package out of this library but I've some troubles. Do you mind to ad a requirements.txt as [this](https://github.com/facebook/prophet/blob/master/python/requirements.txt)?
If neede I can eventually make a PR.

**Comment by tailaiw** [comment]
@rpanai We didn't list a requirements.txt because we list all the dependencies in setup.cfg and that is enough for pip installation. I never made conda packages before but great to hear you are adding ADTK to conda-forge. Feel free to create a requirements.txt based on the dependency list in setup.cfg and open a PR.
